language: ruby
rvm:
- 2.2.2
branches:
  only:
  - master
install:
- git config --global user.email "NSCoderNight@users.noreply.github.com"
- git config --global user.name  "NSCoderNight"
- echo -e "machine github.com\n  login $GH_TOKEN" >> ~/.netrc
- rake bootstrap
script:
- git remote set-url origin "https://github.com/NSCoderNight/NSCoderNight.git"
- bundle exec rake deploy
