# Site settings
title: NSCoderNight
description: > # this means to ignore newlines until "baseurl:"
  Socialize while you serialize
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nscodernight.com" # the base hostname & protocol for your site
twitter_username: nscodernight
github_username:  nscodernight

# Build settings
markdown: kramdown
